CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS rubricas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    curso VARCHAR(100) NOT NULL,
    descripcion TEXT,
    creador VARCHAR(100) NOT NULL,
    criterios TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evaluaciones (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    estudiante VARCHAR(100) NOT NULL,
    rubrica_id BIGINT NOT NULL,
    curso VARCHAR(100) NOT NULL,
    puntaje VARCHAR(20) NOT NULL,
    criterio1 VARCHAR(30),
    criterio2 VARCHAR(30),
    criterio3 VARCHAR(30),
    criterio4 VARCHAR(30),
    criterio5 VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observacion TEXT
);

ALTER TABLE evaluaciones ADD COLUMN IF NOT EXISTS criterio1 VARCHAR(30);
ALTER TABLE evaluaciones ADD COLUMN IF NOT EXISTS criterio2 VARCHAR(30);
ALTER TABLE evaluaciones ADD COLUMN IF NOT EXISTS criterio3 VARCHAR(30);
ALTER TABLE evaluaciones ADD COLUMN IF NOT EXISTS criterio4 VARCHAR(30);
ALTER TABLE evaluaciones ADD COLUMN IF NOT EXISTS criterio5 VARCHAR(30);
ALTER TABLE evaluaciones ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
